version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:///data/pokemon.db
      - PORT=3004
      - HOST=0.0.0.0
    volumes:
      - backend-data:/data
    networks:
      - pokemon-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:80"
    depends_on:
      - backend  # Asegura que el backend esté corriendo antes de iniciar el frontend
    networks:
      - pokemon-network

networks:
  pokemon-network:
    driver: bridge

volumes:
  backend-data:
